import { Skill } from "./types";

export const skills: Skill[] = [
  {
    id: "tdd-workflow",
    name: "Test-Driven Development",
    slug: "test-driven-development",
    description:
      "Enforces red-green-refactor TDD cycle before writing any implementation code. Writes failing tests first, then minimal code to pass.",
    longDescription:
      "A rigid workflow skill that ensures every feature or bugfix starts with a failing test. The agent writes the test, watches it fail, writes the minimum implementation to make it pass, then refactors. Prevents over-engineering and ensures comprehensive test coverage by default.",
    category: "engineering",
    tags: ["testing", "tdd", "workflow", "quality"],
    creator: "Superpowers",
    organization: "Claude Plugins",
    platforms: ["claude-code", "codex", "gemini-cli"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    featured: true,
    createdAt: "2025-11-15",
  },
  {
    id: "systematic-debugging",
    name: "Systematic Debugging",
    slug: "systematic-debugging",
    description:
      "Scientific method for bug investigation. Forms hypotheses, designs experiments, isolates variables — never guesses at fixes.",
    longDescription:
      "Replaces random fix attempts with a structured debugging methodology. The agent gathers evidence, forms hypotheses ranked by likelihood, designs targeted experiments to test each hypothesis, and only proposes fixes after root cause is confirmed. Tracks debugging state across context resets.",
    category: "engineering",
    tags: ["debugging", "workflow", "investigation"],
    creator: "Superpowers",
    organization: "Claude Plugins",
    platforms: ["claude-code", "codex", "gemini-cli"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    featured: true,
    createdAt: "2025-11-15",
  },
  {
    id: "frontend-design",
    name: "Frontend Design",
    slug: "frontend-design",
    description:
      "Creates distinctive, production-grade frontend interfaces with high design quality. Fights AI-slop aesthetics with bold creative direction.",
    longDescription:
      "Guides creation of frontend interfaces that avoid generic 'AI-generated' aesthetics. Enforces strong typographic choices, intentional color palettes, and cohesive design systems. Includes comprehensive reference materials for typography, color, spatial design, motion, and responsive patterns.",
    category: "design",
    tags: ["frontend", "ui", "css", "design-system", "web"],
    creator: "Superpowers",
    organization: "Claude Plugins",
    platforms: ["claude-code", "cursor", "windsurf"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    featured: true,
    createdAt: "2025-12-01",
  },
  {
    id: "code-review",
    name: "Code Review",
    slug: "code-review",
    description:
      "Reviews completed implementation against original plan and coding standards. Catches regressions, security issues, and style violations.",
    category: "engineering",
    tags: ["review", "quality", "standards"],
    creator: "Superpowers",
    organization: "Claude Plugins",
    platforms: ["claude-code", "codex"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2025-11-15",
  },
  {
    id: "brainstorming",
    name: "Brainstorming",
    slug: "brainstorming",
    description:
      "Structured creative exploration before implementation. Generates multiple approaches, evaluates trade-offs, and builds alignment.",
    category: "productivity",
    tags: ["ideation", "planning", "creative", "architecture"],
    creator: "Superpowers",
    organization: "Claude Plugins",
    platforms: ["claude-code", "codex", "gemini-cli"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2025-11-15",
  },
  {
    id: "plan-writing",
    name: "Implementation Planning",
    slug: "implementation-planning",
    description:
      "Creates detailed, step-by-step implementation plans from specs or requirements. Identifies dependencies, risks, and review checkpoints.",
    category: "productivity",
    tags: ["planning", "architecture", "specs", "workflow"],
    creator: "Superpowers",
    organization: "Claude Plugins",
    platforms: ["claude-code", "codex", "gemini-cli"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2025-11-15",
  },
  {
    id: "git-worktrees",
    name: "Git Worktrees",
    slug: "git-worktrees",
    description:
      "Isolates feature work in git worktrees for parallel development without branch-switching overhead.",
    category: "engineering",
    tags: ["git", "workflow", "parallel", "isolation"],
    creator: "Superpowers",
    organization: "Claude Plugins",
    platforms: ["claude-code"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2025-12-10",
  },
  {
    id: "animate",
    name: "Animate",
    slug: "animate",
    description:
      "Enhances UI features with purposeful animations, micro-interactions, and motion effects that improve usability and delight.",
    category: "design",
    tags: ["animation", "motion", "ux", "framer-motion"],
    creator: "Superpowers",
    organization: "Claude Plugins",
    platforms: ["claude-code", "cursor"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2025-12-01",
  },
  {
    id: "polish",
    name: "Polish",
    slug: "polish",
    description:
      "Final quality pass before shipping. Fixes alignment, spacing, consistency, and micro-details that separate good from great.",
    category: "design",
    tags: ["quality", "detail", "finishing", "review"],
    creator: "Superpowers",
    organization: "Claude Plugins",
    platforms: ["claude-code", "cursor"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2025-12-01",
  },
  {
    id: "gsd-workflow",
    name: "GSD (Get Stuff Done)",
    slug: "gsd-workflow",
    description:
      "Full project lifecycle management — from research and roadmapping through phase planning, execution, and verification.",
    longDescription:
      "A comprehensive project management framework for AI agents. Handles project initialization, milestone planning, phase breakdown, parallel execution with wave-based task scheduling, atomic commits, and goal-backward verification. Includes research, debugging, and integration checking subworkflows.",
    category: "productivity",
    tags: ["project-management", "lifecycle", "execution", "planning"],
    creator: "Get Stuff Done",
    organization: "GSD",
    platforms: ["claude-code"],
    sourceUrl: "https://github.com/cyanheads/get-stuff-done",
    featured: true,
    createdAt: "2025-10-20",
  },
  {
    id: "claude-api",
    name: "Claude API Builder",
    slug: "claude-api-builder",
    description:
      "Specialized guidance for building applications with the Claude API, Anthropic SDK, and Agent SDK.",
    category: "engineering",
    tags: ["api", "anthropic", "sdk", "ai"],
    creator: "Superpowers",
    organization: "Claude Plugins",
    platforms: ["claude-code", "codex", "cursor"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2026-01-10",
  },
  {
    id: "audit-accessibility",
    name: "Accessibility Audit",
    slug: "accessibility-audit",
    description:
      "Comprehensive audit of interface quality across accessibility, performance, theming, and responsive design standards.",
    category: "design",
    tags: ["accessibility", "a11y", "audit", "wcag"],
    creator: "Superpowers",
    organization: "Claude Plugins",
    platforms: ["claude-code", "cursor"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2025-12-15",
  },
  {
    id: "ads-google",
    name: "Google Ads Auditor",
    slug: "google-ads-auditor",
    description:
      "Deep analysis covering Search, PMax, Display, YouTube, and Demand Gen campaigns across 74 checks.",
    category: "marketing",
    tags: ["google-ads", "ppc", "audit", "advertising"],
    creator: "Superpowers",
    organization: "Claude Plugins",
    platforms: ["claude-code"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2026-01-05",
  },
  {
    id: "ads-meta",
    name: "Meta Ads Auditor",
    slug: "meta-ads-auditor",
    description:
      "Evaluates 46 checks across Pixel/CAPI health, creative diversity, fatigue signals, and Advantage+ campaigns.",
    category: "marketing",
    tags: ["meta-ads", "facebook", "instagram", "audit"],
    creator: "Superpowers",
    organization: "Claude Plugins",
    platforms: ["claude-code"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2026-01-05",
  },
  {
    id: "skill-creator",
    name: "Skill Creator",
    slug: "skill-creator",
    description:
      "Create, modify, and evaluate AI agent skills. Guides the full lifecycle from ideation to deployment and performance measurement.",
    category: "meta",
    tags: ["skills", "creation", "meta", "authoring"],
    creator: "Superpowers",
    organization: "Claude Plugins",
    platforms: ["claude-code"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2026-02-01",
  },
  {
    id: "mcp-builder",
    name: "MCP Server Builder",
    slug: "mcp-server-builder",
    description:
      "Build Model Context Protocol servers with best practices for tool definitions, resource management, and error handling.",
    category: "engineering",
    tags: ["mcp", "protocol", "server", "tools"],
    creator: "Community",
    platforms: ["claude-code", "cursor"],
    createdAt: "2025-12-20",
  },
  {
    id: "docker-compose",
    name: "Docker Compose Architect",
    slug: "docker-compose-architect",
    description:
      "Designs multi-service Docker Compose configurations with proper networking, volumes, health checks, and production patterns.",
    category: "devops",
    tags: ["docker", "containers", "orchestration", "infra"],
    creator: "Community",
    platforms: ["claude-code", "codex", "gemini-cli", "cursor"],
    createdAt: "2025-11-01",
  },
  {
    id: "ci-cd-pipeline",
    name: "CI/CD Pipeline Design",
    slug: "ci-cd-pipeline-design",
    description:
      "Creates GitHub Actions, GitLab CI, or other CI/CD pipelines with caching, matrix builds, and deployment stages.",
    category: "devops",
    tags: ["ci-cd", "github-actions", "automation", "deployment"],
    creator: "Community",
    platforms: ["claude-code", "codex", "gemini-cli"],
    createdAt: "2025-10-15",
  },
  {
    id: "seo-optimizer",
    name: "SEO Technical Audit",
    slug: "seo-technical-audit",
    description:
      "Analyzes and optimizes technical SEO: meta tags, structured data, Core Web Vitals, sitemap, and crawlability.",
    category: "marketing",
    tags: ["seo", "performance", "audit", "web"],
    creator: "Community",
    platforms: ["claude-code", "cursor"],
    createdAt: "2025-11-20",
  },
  {
    id: "api-design",
    name: "REST API Designer",
    slug: "rest-api-designer",
    description:
      "Designs RESTful APIs with consistent conventions, proper status codes, pagination, error handling, and OpenAPI documentation.",
    category: "engineering",
    tags: ["api", "rest", "openapi", "backend"],
    creator: "Community",
    platforms: ["claude-code", "codex", "gemini-cli", "cursor"],
    createdAt: "2025-09-15",
  },
  {
    id: "database-migration",
    name: "Database Migration Planner",
    slug: "database-migration-planner",
    description:
      "Plans safe database schema migrations with rollback strategies, zero-downtime approaches, and data integrity checks.",
    category: "engineering",
    tags: ["database", "migration", "schema", "sql"],
    creator: "Community",
    platforms: ["claude-code", "codex"],
    createdAt: "2025-10-01",
  },
  {
    id: "web-research",
    name: "Deep Web Research",
    slug: "deep-web-research",
    description:
      "Conducts structured multi-source web research with citation tracking, fact verification, and synthesized reports.",
    category: "research",
    tags: ["research", "web", "analysis", "synthesis"],
    creator: "Community",
    platforms: ["claude-code", "gemini-cli"],
    createdAt: "2025-11-10",
  },
  {
    id: "refactoring",
    name: "Code Simplifier",
    slug: "code-simplifier",
    description:
      "Simplifies and refines code for clarity, consistency, and maintainability while preserving all functionality.",
    category: "engineering",
    tags: ["refactoring", "cleanup", "quality", "maintenance"],
    creator: "Superpowers",
    organization: "Claude Plugins",
    platforms: ["claude-code", "codex", "cursor"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2025-11-15",
  },
  {
    id: "landing-page",
    name: "Landing Page Optimizer",
    slug: "landing-page-optimizer",
    description:
      "Evaluates landing page quality for paid campaigns: message match, speed, mobile UX, trust signals, and conversion paths.",
    category: "marketing",
    tags: ["landing-page", "conversion", "ux", "optimization"],
    creator: "Superpowers",
    organization: "Claude Plugins",
    platforms: ["claude-code"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2026-01-10",
  },
  {
    id: "parallel-agents",
    name: "Parallel Agent Dispatch",
    slug: "parallel-agent-dispatch",
    description:
      "Orchestrates multiple independent sub-agents working in parallel on isolated tasks with coordinated results.",
    category: "productivity",
    tags: ["agents", "parallel", "orchestration", "efficiency"],
    creator: "Superpowers",
    organization: "Claude Plugins",
    platforms: ["claude-code"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2025-12-20",
  },
  {
    id: "adapt",
    name: "Adapt",
    slug: "adapt",
    description:
      "Adapt designs to work across different screen sizes, devices, contexts, or platforms. Ensures consistent experience across varied environments.",
    category: "design",
    tags: ["responsive", "mobile", "cross-platform", "ux"],
    creator: "Impeccable",
    organization: "Claude Plugins",
    platforms: ["claude-code", "cursor"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2026-01-15",
  },
  {
    id: "bolder",
    name: "Bolder",
    slug: "bolder",
    description:
      "Amplify safe or boring designs to make them more visually interesting and stimulating. Increases impact while maintaining usability.",
    category: "design",
    tags: ["visual-design", "typography", "impact", "creative"],
    creator: "Impeccable",
    organization: "Claude Plugins",
    platforms: ["claude-code", "cursor"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2026-01-15",
  },
  {
    id: "clarify",
    name: "Clarify",
    slug: "clarify",
    description:
      "Improve unclear UX copy, error messages, microcopy, labels, and instructions. Makes interfaces easier to understand and use.",
    category: "design",
    tags: ["ux-writing", "microcopy", "clarity", "copywriting"],
    creator: "Impeccable",
    organization: "Claude Plugins",
    platforms: ["claude-code", "cursor"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2026-01-15",
  },
  {
    id: "colorize",
    name: "Colorize",
    slug: "colorize",
    description:
      "Add strategic color to features that are too monochromatic or lack visual interest. Makes interfaces more engaging and expressive.",
    category: "design",
    tags: ["color", "visual-design", "branding", "aesthetic"],
    creator: "Impeccable",
    organization: "Claude Plugins",
    platforms: ["claude-code", "cursor"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2026-01-15",
  },
  {
    id: "critique",
    name: "Critique",
    slug: "critique",
    description:
      "Evaluate design effectiveness from a UX perspective. Assesses visual hierarchy, information architecture, emotional resonance, and overall design quality.",
    category: "design",
    tags: ["design-review", "feedback", "ux", "evaluation"],
    creator: "Impeccable",
    organization: "Claude Plugins",
    platforms: ["claude-code", "cursor"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2026-01-15",
  },
  {
    id: "delight",
    name: "Delight",
    slug: "delight",
    description:
      "Add moments of joy, personality, and unexpected touches that make interfaces memorable and enjoyable to use.",
    category: "design",
    tags: ["micro-interactions", "personality", "ux", "engagement"],
    creator: "Impeccable",
    organization: "Claude Plugins",
    platforms: ["claude-code", "cursor"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2026-01-15",
  },
  {
    id: "distill",
    name: "Distill",
    slug: "distill",
    description:
      "Strip designs to their essence by removing unnecessary complexity. Great design is simple, powerful, and clean.",
    category: "design",
    tags: ["simplification", "minimalism", "clarity", "refinement"],
    creator: "Impeccable",
    organization: "Claude Plugins",
    platforms: ["claude-code", "cursor"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2026-01-15",
  },
  {
    id: "extract",
    name: "Extract",
    slug: "extract",
    description:
      "Extract and consolidate reusable components, design tokens, and patterns into your design system.",
    category: "design",
    tags: ["design-system", "components", "tokens", "refactoring"],
    creator: "Impeccable",
    organization: "Claude Plugins",
    platforms: ["claude-code", "cursor"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2026-01-15",
  },
  {
    id: "harden",
    name: "Harden",
    slug: "harden",
    description:
      "Improve interface resilience through better error handling, i18n support, text overflow handling, and edge case management.",
    category: "design",
    tags: ["error-handling", "i18n", "edge-cases", "robustness"],
    creator: "Impeccable",
    organization: "Claude Plugins",
    platforms: ["claude-code", "cursor"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2026-01-15",
  },
  {
    id: "normalize",
    name: "Normalize",
    slug: "normalize",
    description:
      "Normalize design to match your design system and ensure consistency across all components and pages.",
    category: "design",
    tags: ["design-system", "consistency", "standards", "uniformity"],
    creator: "Impeccable",
    organization: "Claude Plugins",
    platforms: ["claude-code", "cursor"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2026-01-15",
  },
  {
    id: "onboard",
    name: "Onboard",
    slug: "onboard",
    description:
      "Design or improve onboarding flows, empty states, and first-time user experiences. Helps users get started successfully.",
    category: "design",
    tags: ["onboarding", "empty-states", "user-education", "ux"],
    creator: "Impeccable",
    organization: "Claude Plugins",
    platforms: ["claude-code", "cursor"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2026-01-15",
  },
  {
    id: "optimize-ui",
    name: "Optimize",
    slug: "optimize",
    description:
      "Improve interface performance across loading speed, rendering, animations, images, and bundle size.",
    category: "design",
    tags: ["performance", "web-vitals", "speed", "optimization"],
    creator: "Impeccable",
    organization: "Claude Plugins",
    platforms: ["claude-code", "cursor"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2026-01-15",
  },
  {
    id: "quieter",
    name: "Quieter",
    slug: "quieter",
    description:
      "Tone down overly bold or visually aggressive designs. Reduces intensity while maintaining design quality and impact.",
    category: "design",
    tags: ["subtlety", "refinement", "visual-design", "balance"],
    creator: "Impeccable",
    organization: "Claude Plugins",
    platforms: ["claude-code", "cursor"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2026-01-15",
  },
  {
    id: "teach-impeccable",
    name: "Teach Impeccable",
    slug: "teach-impeccable",
    description:
      "One-time setup that gathers design context for your project and saves it to your AI config file. Establishes persistent design guidelines.",
    category: "meta",
    tags: ["design-system", "setup", "guidelines", "configuration"],
    creator: "Impeccable",
    organization: "Claude Plugins",
    platforms: ["claude-code"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2026-01-15",
  },
  {
    id: "ads-comprehensive",
    name: "Paid Ads Audit",
    slug: "paid-ads-audit",
    description:
      "Comprehensive paid advertising audit and optimization across Google, Meta, LinkedIn, TikTok, and Microsoft platforms.",
    category: "marketing",
    tags: ["advertising", "ppc", "audit", "multi-platform"],
    creator: "Superpowers",
    organization: "Claude Plugins",
    platforms: ["claude-code"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2026-01-05",
  },
  {
    id: "ads-audit",
    name: "Multi-Platform Ad Audit",
    slug: "multi-platform-ad-audit",
    description:
      "Full multi-platform paid advertising audit with parallel subagent delegation. Generates health scores per platform and aggregate score.",
    category: "marketing",
    tags: ["advertising", "audit", "health-score", "analytics"],
    creator: "Superpowers",
    organization: "Claude Plugins",
    platforms: ["claude-code"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2026-01-05",
  },
  {
    id: "ads-budget",
    name: "Ad Budget Optimizer",
    slug: "ad-budget-optimizer",
    description:
      "Budget allocation and bidding strategy review across all ad platforms. Evaluates spend distribution and scaling readiness.",
    category: "marketing",
    tags: ["advertising", "budget", "bidding", "strategy"],
    creator: "Superpowers",
    organization: "Claude Plugins",
    platforms: ["claude-code"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2026-01-05",
  },
  {
    id: "ads-competitor",
    name: "Competitor Ad Intel",
    slug: "competitor-ad-intel",
    description:
      "Competitor ad intelligence analysis across Google, Meta, LinkedIn, TikTok, and Microsoft. Analyzes competitor strategy and positioning.",
    category: "marketing",
    tags: ["advertising", "competitor-analysis", "intelligence", "strategy"],
    creator: "Superpowers",
    organization: "Claude Plugins",
    platforms: ["claude-code"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2026-01-05",
  },
  {
    id: "ads-creative",
    name: "Creative Quality Audit",
    slug: "creative-quality-audit",
    description:
      "Cross-platform creative quality audit covering ad copy, video, image, and format diversity. Detects creative fatigue.",
    category: "marketing",
    tags: ["advertising", "creative", "quality", "copywriting"],
    creator: "Superpowers",
    organization: "Claude Plugins",
    platforms: ["claude-code"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2026-01-05",
  },
  {
    id: "ads-linkedin",
    name: "LinkedIn Ads Auditor",
    slug: "linkedin-ads-auditor",
    description:
      "LinkedIn Ads deep analysis for B2B advertising. Evaluates 25 checks across technical setup, audience targeting, and lead gen.",
    category: "marketing",
    tags: ["linkedin", "b2b", "lead-gen", "advertising"],
    creator: "Superpowers",
    organization: "Claude Plugins",
    platforms: ["claude-code"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2026-01-05",
  },
  {
    id: "ads-microsoft",
    name: "Microsoft Ads Auditor",
    slug: "microsoft-ads-auditor",
    description:
      "Microsoft/Bing Ads deep analysis covering search, Performance Max, Audience Network, and Copilot integration.",
    category: "marketing",
    tags: ["microsoft", "bing", "ppc", "advertising"],
    creator: "Superpowers",
    organization: "Claude Plugins",
    platforms: ["claude-code"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2026-01-05",
  },
  {
    id: "ads-plan",
    name: "Ad Campaign Planner",
    slug: "ad-campaign-planner",
    description:
      "Strategic paid advertising planning with industry-specific templates. Covers platform selection, campaign architecture, and budget allocation.",
    category: "marketing",
    tags: ["advertising", "strategy", "planning", "campaign"],
    creator: "Superpowers",
    organization: "Claude Plugins",
    platforms: ["claude-code"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2026-01-05",
  },
  {
    id: "ads-tiktok",
    name: "TikTok Ads Auditor",
    slug: "tiktok-ads-auditor",
    description:
      "TikTok Ads deep analysis covering creative quality, tracking, bidding, campaign structure, and TikTok Shop.",
    category: "marketing",
    tags: ["tiktok", "creative", "video", "advertising"],
    creator: "Superpowers",
    organization: "Claude Plugins",
    platforms: ["claude-code"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2026-01-05",
  },
  {
    id: "ads-youtube",
    name: "YouTube Ads Auditor",
    slug: "youtube-ads-auditor",
    description:
      "YouTube Ads analysis covering campaign types, creative quality, audience targeting, and measurement across all video formats.",
    category: "marketing",
    tags: ["youtube", "video", "advertising", "google"],
    creator: "Superpowers",
    organization: "Claude Plugins",
    platforms: ["claude-code"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2026-01-05",
  },
  {
    id: "para-memory",
    name: "PARA Memory System",
    slug: "para-memory-system",
    description:
      "File-based memory system using Tiago Forte's PARA method. Store, retrieve, update, and organize knowledge across sessions.",
    category: "productivity",
    tags: ["memory", "knowledge-base", "organization", "workflow"],
    creator: "Community",
    platforms: ["claude-code"],
    createdAt: "2026-02-01",
  },
];
