import { Skill } from "./types";

export const skills: Skill[] = [
  {
    id: "tdd-workflow",
    name: "Test-Driven Development",
    slug: "test-driven-development",
    description:
      "Enforces red-green-refactor TDD cycle before writing any implementation code. Writes failing tests first, then minimal code to pass.",
    longDescription:
      "A rigid workflow skill that ensures every feature or bugfix starts with a failing test. The agent writes the test, watches it fail, writes the minimum implementation to make it pass, then refactors. Prevents over-engineering and ensures comprehensive test coverage by default.",
    category: "engineering",
    tags: ["testing", "tdd", "workflow", "quality"],
    creator: "Superpowers",
    organization: "Claude Plugins",
    platforms: ["claude-code", "codex", "gemini-cli"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    featured: true,
    createdAt: "2025-11-15",
  },
  {
    id: "systematic-debugging",
    name: "Systematic Debugging",
    slug: "systematic-debugging",
    description:
      "Scientific method for bug investigation. Forms hypotheses, designs experiments, isolates variables — never guesses at fixes.",
    longDescription:
      "Replaces random fix attempts with a structured debugging methodology. The agent gathers evidence, forms hypotheses ranked by likelihood, designs targeted experiments to test each hypothesis, and only proposes fixes after root cause is confirmed. Tracks debugging state across context resets.",
    category: "engineering",
    tags: ["debugging", "workflow", "investigation"],
    creator: "Superpowers",
    organization: "Claude Plugins",
    platforms: ["claude-code", "codex", "gemini-cli"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    featured: true,
    createdAt: "2025-11-15",
  },
  {
    id: "frontend-design",
    name: "Frontend Design",
    slug: "frontend-design",
    description:
      "Creates distinctive, production-grade frontend interfaces with high design quality. Fights AI-slop aesthetics with bold creative direction.",
    longDescription:
      "Guides creation of frontend interfaces that avoid generic 'AI-generated' aesthetics. Enforces strong typographic choices, intentional color palettes, and cohesive design systems. Includes comprehensive reference materials for typography, color, spatial design, motion, and responsive patterns.",
    category: "design",
    tags: ["frontend", "ui", "css", "design-system", "web"],
    creator: "Superpowers",
    organization: "Claude Plugins",
    platforms: ["claude-code", "cursor", "windsurf"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    featured: true,
    createdAt: "2025-12-01",
  },
  {
    id: "code-review",
    name: "Code Review",
    slug: "code-review",
    description:
      "Reviews completed implementation against original plan and coding standards. Catches regressions, security issues, and style violations.",
    category: "engineering",
    tags: ["review", "quality", "standards"],
    creator: "Superpowers",
    organization: "Claude Plugins",
    platforms: ["claude-code", "codex"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2025-11-15",
  },
  {
    id: "brainstorming",
    name: "Brainstorming",
    slug: "brainstorming",
    description:
      "Structured creative exploration before implementation. Generates multiple approaches, evaluates trade-offs, and builds alignment.",
    category: "productivity",
    tags: ["ideation", "planning", "creative", "architecture"],
    creator: "Superpowers",
    organization: "Claude Plugins",
    platforms: ["claude-code", "codex", "gemini-cli"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2025-11-15",
  },
  {
    id: "plan-writing",
    name: "Implementation Planning",
    slug: "implementation-planning",
    description:
      "Creates detailed, step-by-step implementation plans from specs or requirements. Identifies dependencies, risks, and review checkpoints.",
    category: "productivity",
    tags: ["planning", "architecture", "specs", "workflow"],
    creator: "Superpowers",
    organization: "Claude Plugins",
    platforms: ["claude-code", "codex", "gemini-cli"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2025-11-15",
  },
  {
    id: "git-worktrees",
    name: "Git Worktrees",
    slug: "git-worktrees",
    description:
      "Isolates feature work in git worktrees for parallel development without branch-switching overhead.",
    category: "engineering",
    tags: ["git", "workflow", "parallel", "isolation"],
    creator: "Superpowers",
    organization: "Claude Plugins",
    platforms: ["claude-code"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2025-12-10",
  },
  {
    id: "animate",
    name: "Animate",
    slug: "animate",
    description:
      "Enhances UI features with purposeful animations, micro-interactions, and motion effects that improve usability and delight.",
    category: "design",
    tags: ["animation", "motion", "ux", "framer-motion"],
    creator: "Superpowers",
    organization: "Claude Plugins",
    platforms: ["claude-code", "cursor"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2025-12-01",
  },
  {
    id: "polish",
    name: "Polish",
    slug: "polish",
    description:
      "Final quality pass before shipping. Fixes alignment, spacing, consistency, and micro-details that separate good from great.",
    category: "design",
    tags: ["quality", "detail", "finishing", "review"],
    creator: "Superpowers",
    organization: "Claude Plugins",
    platforms: ["claude-code", "cursor"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2025-12-01",
  },
  {
    id: "gsd-workflow",
    name: "GSD (Get Stuff Done)",
    slug: "gsd-workflow",
    description:
      "Full project lifecycle management — from research and roadmapping through phase planning, execution, and verification.",
    longDescription:
      "A comprehensive project management framework for AI agents. Handles project initialization, milestone planning, phase breakdown, parallel execution with wave-based task scheduling, atomic commits, and goal-backward verification. Includes research, debugging, and integration checking subworkflows.",
    category: "productivity",
    tags: ["project-management", "lifecycle", "execution", "planning"],
    creator: "Get Stuff Done",
    organization: "GSD",
    platforms: ["claude-code"],
    sourceUrl: "https://github.com/cyanheads/get-stuff-done",
    featured: true,
    createdAt: "2025-10-20",
  },
  {
    id: "claude-api",
    name: "Claude API Builder",
    slug: "claude-api-builder",
    description:
      "Specialized guidance for building applications with the Claude API, Anthropic SDK, and Agent SDK.",
    category: "engineering",
    tags: ["api", "anthropic", "sdk", "ai"],
    creator: "Superpowers",
    organization: "Claude Plugins",
    platforms: ["claude-code", "codex", "cursor"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2026-01-10",
  },
  {
    id: "audit-accessibility",
    name: "Accessibility Audit",
    slug: "accessibility-audit",
    description:
      "Comprehensive audit of interface quality across accessibility, performance, theming, and responsive design standards.",
    category: "design",
    tags: ["accessibility", "a11y", "audit", "wcag"],
    creator: "Superpowers",
    organization: "Claude Plugins",
    platforms: ["claude-code", "cursor"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2025-12-15",
  },
  {
    id: "ads-google",
    name: "Google Ads Auditor",
    slug: "google-ads-auditor",
    description:
      "Deep analysis covering Search, PMax, Display, YouTube, and Demand Gen campaigns across 74 checks.",
    category: "marketing",
    tags: ["google-ads", "ppc", "audit", "advertising"],
    creator: "Superpowers",
    organization: "Claude Plugins",
    platforms: ["claude-code"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2026-01-05",
  },
  {
    id: "ads-meta",
    name: "Meta Ads Auditor",
    slug: "meta-ads-auditor",
    description:
      "Evaluates 46 checks across Pixel/CAPI health, creative diversity, fatigue signals, and Advantage+ campaigns.",
    category: "marketing",
    tags: ["meta-ads", "facebook", "instagram", "audit"],
    creator: "Superpowers",
    organization: "Claude Plugins",
    platforms: ["claude-code"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2026-01-05",
  },
  {
    id: "skill-creator",
    name: "Skill Creator",
    slug: "skill-creator",
    description:
      "Create, modify, and evaluate AI agent skills. Guides the full lifecycle from ideation to deployment and performance measurement.",
    category: "meta",
    tags: ["skills", "creation", "meta", "authoring"],
    creator: "Superpowers",
    organization: "Claude Plugins",
    platforms: ["claude-code"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2026-02-01",
  },
  {
    id: "mcp-builder",
    name: "MCP Server Builder",
    slug: "mcp-server-builder",
    description:
      "Build Model Context Protocol servers with best practices for tool definitions, resource management, and error handling.",
    category: "engineering",
    tags: ["mcp", "protocol", "server", "tools"],
    creator: "Community",
    platforms: ["claude-code", "cursor"],
    createdAt: "2025-12-20",
  },
  {
    id: "docker-compose",
    name: "Docker Compose Architect",
    slug: "docker-compose-architect",
    description:
      "Designs multi-service Docker Compose configurations with proper networking, volumes, health checks, and production patterns.",
    category: "devops",
    tags: ["docker", "containers", "orchestration", "infra"],
    creator: "Community",
    platforms: ["claude-code", "codex", "gemini-cli", "cursor"],
    createdAt: "2025-11-01",
  },
  {
    id: "ci-cd-pipeline",
    name: "CI/CD Pipeline Design",
    slug: "ci-cd-pipeline-design",
    description:
      "Creates GitHub Actions, GitLab CI, or other CI/CD pipelines with caching, matrix builds, and deployment stages.",
    category: "devops",
    tags: ["ci-cd", "github-actions", "automation", "deployment"],
    creator: "Community",
    platforms: ["claude-code", "codex", "gemini-cli"],
    createdAt: "2025-10-15",
  },
  {
    id: "seo-optimizer",
    name: "SEO Technical Audit",
    slug: "seo-technical-audit",
    description:
      "Analyzes and optimizes technical SEO: meta tags, structured data, Core Web Vitals, sitemap, and crawlability.",
    category: "marketing",
    tags: ["seo", "performance", "audit", "web"],
    creator: "Community",
    platforms: ["claude-code", "cursor"],
    createdAt: "2025-11-20",
  },
  {
    id: "api-design",
    name: "REST API Designer",
    slug: "rest-api-designer",
    description:
      "Designs RESTful APIs with consistent conventions, proper status codes, pagination, error handling, and OpenAPI documentation.",
    category: "engineering",
    tags: ["api", "rest", "openapi", "backend"],
    creator: "Community",
    platforms: ["claude-code", "codex", "gemini-cli", "cursor"],
    createdAt: "2025-09-15",
  },
  {
    id: "database-migration",
    name: "Database Migration Planner",
    slug: "database-migration-planner",
    description:
      "Plans safe database schema migrations with rollback strategies, zero-downtime approaches, and data integrity checks.",
    category: "engineering",
    tags: ["database", "migration", "schema", "sql"],
    creator: "Community",
    platforms: ["claude-code", "codex"],
    createdAt: "2025-10-01",
  },
  {
    id: "web-research",
    name: "Deep Web Research",
    slug: "deep-web-research",
    description:
      "Conducts structured multi-source web research with citation tracking, fact verification, and synthesized reports.",
    category: "research",
    tags: ["research", "web", "analysis", "synthesis"],
    creator: "Community",
    platforms: ["claude-code", "gemini-cli"],
    createdAt: "2025-11-10",
  },
  {
    id: "refactoring",
    name: "Code Simplifier",
    slug: "code-simplifier",
    description:
      "Simplifies and refines code for clarity, consistency, and maintainability while preserving all functionality.",
    category: "engineering",
    tags: ["refactoring", "cleanup", "quality", "maintenance"],
    creator: "Superpowers",
    organization: "Claude Plugins",
    platforms: ["claude-code", "codex", "cursor"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2025-11-15",
  },
  {
    id: "landing-page",
    name: "Landing Page Optimizer",
    slug: "landing-page-optimizer",
    description:
      "Evaluates landing page quality for paid campaigns: message match, speed, mobile UX, trust signals, and conversion paths.",
    category: "marketing",
    tags: ["landing-page", "conversion", "ux", "optimization"],
    creator: "Superpowers",
    organization: "Claude Plugins",
    platforms: ["claude-code"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2026-01-10",
  },
  {
    id: "parallel-agents",
    name: "Parallel Agent Dispatch",
    slug: "parallel-agent-dispatch",
    description:
      "Orchestrates multiple independent sub-agents working in parallel on isolated tasks with coordinated results.",
    category: "productivity",
    tags: ["agents", "parallel", "orchestration", "efficiency"],
    creator: "Superpowers",
    organization: "Claude Plugins",
    platforms: ["claude-code"],
    sourceUrl: "https://github.com/nichochar/superpowers",
    createdAt: "2025-12-20",
  },
];
